version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      # Docker環境專用設定
      - NEXTAUTH_URL=http://localhost:3002
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run dev -- -p 3002"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: