version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:devpassword@db:5432/yyselection
      - NEXTAUTH_URL=http://localhost:3002
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run dev -- -p 3002"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: yyselection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: